# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MjXc33vEQwqOudTlHc3e0iRKg21BCVdO
"""

import requests
from bs4 import BeautifulSoup
import json
def scrape_faculty_expertise(url):
    """
    從亞洲大學資工系網頁抓取每位老師的專長。

    Args:
        url (str): 亞洲大學資工系副教授頁面的 URL。

    Returns:
        dict: 一個字典，鍵是老師的名字，值是他們的專長。
              如果發生錯誤，則返回 None。
    """
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.content, 'html.parser')
        faculty_list = soup.select('.et_pb_team_member')
        expertise_data = {}
        for faculty in faculty_list:
            name_element = faculty.select_one('.et_pb_team_member_header h3')
            expertise_element = faculty.select_one('.et_pb_team_member_description')

            if name_element and expertise_element:
                name = name_element.text.strip()
                expertise = expertise_element.text.strip().replace("專長 / Discipline expertise:", "").strip()
                expertise_data[name] = expertise
        return expertise_data
    except requests.exceptions.RequestException as e:
        print(f"網路請求錯誤: {e}")
        return None
    except Exception as e:
        print(f"發生錯誤: {e}")
        return None
if __name__ == "__main__":
    url = "https://csie.asia.edu.tw/zh_tw/associate_professors_2"
    faculty_expertise = scrape_faculty_expertise(url)
    if faculty_expertise:
        output_filename_json = "asia_csie_faculty_expertise.json"
        with open(output_filename_json, 'w', encoding='utf-8') as f:
            json.dump(faculty_expertise, f, ensure_ascii=False, indent=4)
        print(f"老師專長已儲存至 {output_filename_json}")
        output_filename_txt = "asia_csie_faculty_expertise.txt"
        with open(output_filename_txt, 'w', encoding='utf-8') as f:
            for name, expertise in faculty_expertise.items():
                f.write(f"老師: {name}\n專長: {expertise}\n\n")
        print(f"老師專長已儲存至 {output_filename_txt}")
        output_filename_csv = "asia_csie_faculty_expertise.csv"
        import csv
        with open(output_filename_csv, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(['老師', '專長'])
            for name, expertise in faculty_expertise.items():
                writer.writerow([name, expertise])
        print(f"老師專長已儲存至 {output_filename_csv}")
    else:
        print("無法抓取老師專長資訊。")